ALTER GIT REPOSITORY IF EXISTS dsmdavid_github_30days FETCH;

CREATE STREAMLIT IF NOT EXISTS dsmdavid_30days_day_05
  FROM @THIRTY_DAYS.COMMON.DSMDAVID_GITHUB_30DAYS/branches/main/app
  MAIN_FILE = 'day05.py'
  QUERY_WAREHOUSE = COMPUTE_WH;


ALTER STREAMLIT dsmdavid_30days_day_05 ADD LIVE VERSION FROM LAST;